// src/services/apiClient.ts
import { ChatApiRequest } from "@/types/chat";

const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";
const API_BASE_URL2 = process.env.NEXT_PUBLIC_API_URL2 || "http://localhost:3000";
const CHAT_API_BASE_URL = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8001";
const AUTH_API_BASE_URL = process.env.NEXT_PUBLIC_AUTH_URL || "http://localhost:8000";

export interface CurrentUser {
  email: string | null;
  role?: string;
  is_sso?: boolean;
}

/**
 * Opens a real-time Server-Sent Events (SSE) stream to the FastAPI backend.
 * Instead of waiting for a full response, it fires the `onChunk` callback 
 * every time a new word (token) is generated by the AI.
 */
export async function streamChatMessage(
  request: ChatApiRequest,
  onChunk: (chunk: string) => void
): Promise<void> {
  try {
    const response = await fetch(`${CHAT_API_BASE_URL}/api/chat`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      credentials: "include", // <--- ADDED THIS LINE to send the SSO cookie
      body: JSON.stringify(request),
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => null);
      throw new Error(errorData?.detail || `Server error: ${response.status}`);
    }

    if (!response.body) throw new Error("No response body from server.");

    // Create a reader to intercept the stream of bytes
    const reader = response.body.getReader();
    const decoder = new TextDecoder("utf-8");
    let buffer = "";

    // Keep reading the pipeline until the server closes it
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;

      // Decode the raw bytes into a string
      buffer += decoder.decode(value, { stream: true });
      
      // SSE sends data separated by two newlines. We split the buffer to process complete packets.
      const parts = buffer.split("\n\n");
      buffer = parts.pop() || ""; // Keep any incomplete packets in the buffer for the next loop

      for (const part of parts) {
        const trimmedPart = part.trim();
        if (trimmedPart.startsWith("data: ")) {
          // Extract the JSON string from the SSE format
          const dataStr = trimmedPart.slice(6); 
          
          if (dataStr === "[DONE]") return; // The server told us the AI is finished thinking

          try {
            const parsed = JSON.parse(dataStr);
            if (parsed.error) {
              throw new Error(parsed.error);
            }
            if (parsed.content) {
              // Send the exact word directly to our React UI
              onChunk(parsed.content);
            }
          } catch {
            // Ignore incomplete JSON chunks (they will be caught on the next pass)
          }
        }
      }
    }
  } catch (error) {
    console.error("Streaming API Client Error:", error);
    throw error;
  }
}

export async function getCurrentUser(): Promise<CurrentUser> {
  const response = await fetch(`${CHAT_API_BASE_URL}/api/user/me`, {
    method: "GET",
    credentials: "include",
    cache: "no-store",
  });

  if (!response.ok) {
    const errorData = await response.json().catch(() => null);
    throw new Error(errorData?.detail || `Server error: ${response.status}`);
  }

  return response.json();
}
export async function getEmployeeDetails() {
  const response = await fetch(`${API_BASE_URL2}/api/employee/details`, {
    method: "GET",
    credentials: "include", 
    cache: "no-store",
  });

  if (!response.ok) {
    const errorData = await response.json().catch(() => null);
    throw new Error(errorData?.detail || `Server error: ${response.status}`);
  }

  const data = await response.json();
  return data.data; // employee object
}
export async function logoutUser(): Promise<void> {
  const response = await fetch(`${AUTH_API_BASE_URL}/api/auth/logout`, {
    method: "POST",
    credentials: "include",
  });

  if (!response.ok) {
    const errorData = await response.json().catch(() => null);
    throw new Error(errorData?.detail || `Server error: ${response.status}`);
  }
}

export interface TimesheetPayload {
  employeeEmail: string;
  weekEnding: string;
  claimMonth: string;
  hours: {
    day1: string;
    day2: string;
    day3: string;
    day4: string;
    day5: string;
    day6: string;
    day7: string;
  };
  status: string;
  remarks: string;
}

export async function submitTimesheet(empId: string, payload: TimesheetPayload) {
  const response = await fetch(`${API_BASE_URL2}/api/employee/${encodeURIComponent(empId)}/timesheet`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify(payload),
  });

  if (!response.ok) {
    const errorData = await response.json().catch(() => null);
    throw new Error(errorData?.message || `Server error: ${response.status}`);
  }

  return response.json();
}
